[project]
name = "otp-via-streamlit"
version = "0.1.0"
description = "OTP sender and verifier using streamlit UI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "streamlit>=1.49.1",
]
